### PR TITLE
feat: add Windows support for xs-dev/tools, ESP32, and ESP8266

### PR DESCRIPTION
**Pull request by andycarle**
This commit merges together everything from PR #53. Initial Windows support for xs-dev, including Moddable SDK tools, ESP32 support, and ESP8266 support.

### CODE REVIEW

**Comment by andycarle** [comment]
Hmmm. pnpm hates me, which is not shocking. @HipsterBrown I'm gathering that I need to check in the updated `pnpm-lock.yaml`? That's simple enough, except that mine is in a slightly weird state because pnpm wanted me to add a missing peer, which I did somewhat blindly. That ended up adding `"rollup": "^2.78.1",` to my `package.json`.

Is the right thing to do here to commit the updated `package.json` and the updated `pnpm-lock.yaml`? (Sorry, I'm only passingly familiar with PNPM and not at all comfortable with how it interacts with git repos.)

**Comment by HipsterBrown** [comment]
> Is the right thing to do here to commit the updated package.json and the updated pnpm-lock.yaml? 

@andycarle Yes, that exactly right. The `pnpm-lock.yaml` ensures the same dependency versions are used on CI and each installation of the package. To resolve the peer dependency warning, be sure to add `rollup` as a dev dependency since it's not required in the released package. 

Be sure to run `pnpm lint` locally to check for any linting warnings (CI will do this as well).

**Comment by andycarle** [comment]
Success, I think? 🎉 A few changes since the previous version of this commit:

- Some little tweaks to appease the linter.
- Updated `pnpm-lock.yaml` and `package.json` as per above.
- Updated URLs for ESP8266 downloads to DropBox. I was having trouble with SSL errors between Axios and Moddable.com that I wasn't prepared to try to hunt down right now.

**Review by HipsterBrown — APPROVED** [review]
🚀

**Comment by HipsterBrown** [comment]
This has been released as v0.18.0 of the CLI! Thanks again for all the great work @andycarle! 👏 I'm really looking forward to the feedback and iterating on future features 😄

**Pull request merged**
